services:
  - type: web
    name: zeno
    repo: https://github.com/Romeoser77/Romeo-MD.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
        
